name: Test
run-name: Test action
on:
  push:
    branches:
      - '*'

jobs:
  Get_infos:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.extract_branch.outputs.branch }}
      token: ${{ steps.extract_token.outputs.token }}
    steps:
      - name: Extract branch name
        shell: bash
        run: |
          echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
        id: extract_branch
        
      - name: Extract token
        shell: bash
        env:
          githubtoken: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "token=$env:githubtoken" >> $GITHUB_OUTPUT
          echo "$env:githubtoken"
        id: extract_token
        
  Routine_Check_for_Commit:
      needs: Get_infos
      uses: ruiheesi/check-action-info/.github/workflows/action.yml@main
      with:
         action: "test"
         githubtoken: ${{ secrets.GITHUB_TOKEN }}
         githubbranch: "${{ needs.Get_infos.outputs.branch }}"
