name: Test
run-name: Test action
on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  Routine_Check_for_Commit:
    runs-on: ubuntu-latest
    steps:
      - uses: ruiheesi/check-action-info@main
        with:
           action: "test"