name: Gitflow Action for R Package Development
run-name: ${{ github.actor }} now ${{ github.event_name }} to ${{ github.ref_name }}

on:
  push:
    branches: ['*', '!dev', '!main']
    
  pull_request:
    types: ['opened', 'closed']
    branches: ['main', 'release*']

jobs:
  User_Inputs:
    runs-on: ubuntu-latest
    env:
      set_image_to_be_used: ghcr.io/ruiheesi/single-cell-rna-r4:latest
      action_version: main
      test: Yes

    steps:
      - name: Print action scripts to be used
        shell: bash
        run: |
          echo "Image: ${{ env.set_image_to_be_used }}"
          echo "Action version to use: ${{ env.action_version }}"
          echo "Run test: ${{ env.test }}"
        
  Activating_Parser:
    needs: [User_Inputs]
    uses: fnlcr-bids-sdsi/gitflow-R/.github/workflows/parser.yml@master
    with:
      image_to_use: ${{ needs.User_Inputs.env.set_image_to_be_used }}
      verions_to_use: ${{ needs.User_Inputs.env.action_version }}
      test: ${{ needs.User_Inputs.env.test }}
      
