name: Test
run-name: Test action
on:
  push:
    branches:
      - '*'

jobs:
  Routine_Check_for_Commit:
      uses: ruiheesi/check-action-info/.github/workflows/action.yml@main
      with:
         action: "test"
         githubtoken: ${{ secrets.GITHUB_TOKEN }}
         githubbranch: ${{ GITHUB_REF#refs/heads/ }}
