name: Test
run-name: Test action

on:
  push:
    branches:
      - '*'
      - '!dev'
      - '!main'
      
  pull_request:
    types:
      - opened
      - closed
    branches:
      - main 
      - release*

jobs:
  Get_infos:
    runs-on: ubuntu-latest
    env:
      githubtoken: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      branch: ${{ steps.extract_branch.outputs.branch }}
      token: ${{ steps.extract_token.outputs.token }}
    steps:
      - name: Extract branch name
        shell: bash
        run: |
          echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
        id: extract_branch
        
      - name: Extract token
        shell: bash
        run: |
          echo "token=$githubtoken" >> $GITHUB_OUTPUT
          echo "$githubtoken"
        id: extract_token
        
  Routine_Check_for_Commit:
      needs: Get_infos
      uses: ruiheesi/check-action-info/.github/workflows/action.yml@main
      with:
         action: "test-not test"
         githubbranch: "${{ needs.Get_infos.outputs.branch }}"
         image_to_use: "ghcr.io/ruiheesi/single-cell-rna-r4:latest"
